### ISSUE TITLE
Critical error causing loss of command sets

### ISSUE THREAD

**Issue by Pinacolada64** [Pinacolada64/NOW#17]
Steps to reproduce:

1. Summon a portal.
2. `enter portal`

NOW does not display output from any commands I tried (`pub <message>`, `tel/to amber`)

Output:

```
 ... Portal lost connection to Server.
 ...
 ...
 ...
 ...
 ...
 ...
 ...
 ...
 ...
 ...
 ...
 ...
 ...
 ...
 ...
 ... Server restarted.

No command sets found! This is a critical bug that can have
multiple causes.

````

**Comment by Pinacolada64** [comment]
And now I can't connect at all. I am sorry. :cry:

**Comment by AmberFennek** [comment]
When a critical error occurs in the server, the object issuing server commands may no longer be known or not have any command sets, so in effect, all command issuing stops as a safety precaution.

The source of this crash is unknown, but we can investigate with an attempt to replicate the crash if you @Pinacolada64 are feeling adventurous.

**Comment by AmberFennek** [comment]
I'm not entirely sure it was due to the upstream bug with inline functions, but I resolved this issue and have portals working again with and without reproducing the critical error, so I will call this issue resolved.

Note that Inline functions are still not usable due to upstream problems, and may or may not have contributed to this issue.
