### ISSUE TITLE
Add FM-style 'morph' command

### ISSUE THREAD

**Issue by drandre2014** [Pinacolada64/NOW#22]
'morph', 'qmorph', and all that good stuff from Fuzzball MUCK-style MUCKs.

**Comment by tricuspa** [comment]
Well we like the idea but we' want to include concept like state change, which may be  a bit of an abstract concept to deal with but it would be inclusive to morph (and for many other things).
For example morph could be by choice... or it could be the result of something for example a seasonal change, folks coats could change from brown to white dependent on the year (automatically even) or as a creature grows older, triceratops growing from nubs to full horns etc.  

So before we think of a "simple" morph we want to consider what would be useful features for the most interesting complexity that are reasonable to do, can you help put together some of those ideas?

**Comment by AmberFennek** [comment]
For the simplest of areas, a morph would consist of changing description to one of several user-defined choices, as well as species, or gender.  There exists a multi-descer contrib that would do this, but it's not a "state change", which is really what morphing is about.  I will begin working on this as early as milestone 2, but anyone can contribute ideas or code until then, even example code.  The MUF code for morph could be used as a reference if anyone wants to gather that.

**Comment by JeeDRGN** [comment]
FM's MORPH command has many bugs, because it lags behind player features.  It might be a good feature to add once everything in NOW is settled for player feature development, but if it is implemented before then, would require very frequent updates.
Besides that, NOW has @IC, which is designed as such:  If you want to be something else, you find the something else (an NPC) and @IC into it to assume that NPC in every way.  Unlike FM, player characters aren't designed to RP with directly in NOW, but are designed to be like the spirits which inhabit the material NPCs in RP zones.
The only addition I'd recommend is documentation to this effect, especially since NOW is advertised on FM.  If Tria likes, I can write some documentation to distinguish the fundamental differences between NOW and FM (and most other MU*s).

**Comment by tricuspa** [comment]
The **morph** command is completed, please test it out at your earliest convenience and report your results here.

**Comment by tricuspa** [comment]
Morph command added!
